AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation sample template for ec2
Parameters:
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.small
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
      - t2.small
Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-03e88be9ecff64781
      InstanceType: !Ref InstanceType
      KeyName: shyam
